---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-php
  labels:
    app: crud-php
  annotations:
    monitoring: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-php
  template:
    metadata:
      labels:
        app: crud-php
    spec:
      containers:
        - env:
            - name: WHATEVER_ENV
              value: WHATEVER_VALUE
          image: bedebhak/project_itdp
          imagePullPolicy: Always
          name: latihan-php
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crud-php-service
spec:
  selector:
    app: crud-php
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer