version: '3.7'
services:
    app:
        build: .
        ports:
            - 81:80
        volumes:
            - .:/var/www/html
    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'db_ummi'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: ""
        volumes:
            - ./db_ummi.sql:/docker-entrypoint-initdb.d/migrate.sql